wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689980700.655104
    t:
      1:
      - 1
      - 50
      - 55
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.15.5
      8:
      - 5
