wandb_version: 1

experiment:
  desc: null
  value: aj3/ppo/ppo_7x7
trainer.agent.entropy_coef:
  desc: null
  value: 0.05093826957501195
trainer.agent.lr:
  desc: null
  value: 0.0003576416294366811
trainer.agent.max_grad_norm:
  desc: null
  value: 0.8482350128241296
trainer.agent.value_loss_coef:
  desc: null
  value: 0.5651002970303038
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689981010.507691
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 16
      - 23
      - 24
      - 37
      4: 3.10.12
      5: 0.15.5
      8:
      - 4
      - 5
