defaults:
  - base_impala_net
  - /net@rnn: base_hooked_transformer_state_encoder


embd_vocab_size: 4
in_dim: ${trainer.env.obs_dim}
out_dim: 4
embd_dim: 8
hidden_dim: 32

scale: 1
rnn:
  n_layers: 2
  d_model: ${..hidden_dim}
  d_head: 64
  n_heads: 8
  n_ctx: 1024
  d_mlp: ${..hidden_dim}

  mode: "algorithmic-distillation"