seed: 1532
log_every: 100
trainer_name: "bc"
net_name: "dt-rtg"
exp_dir: 'exps/bc_oracle'

env:
  max_steps: 100
  num_objects: 1
  agent_visibility: -1
  grid_size: 15
  reward_type: 'distance_to_goal'
  difficulty: 'hard'
  static_env: False

train:
  bc_teacher_trainer: "algorithmic"
  bc_teacher_net: "shortest-path"
  scale: 1
  num_steps: 100000
  value_coef: 0.5
  entropy_coef: 0.1
  epsilon: 0.2
  max_steps: 100
  num_envs: 40
  hidden_size: 256
  embd_dim: 32
  lr: 0.001
  ppo_epochs: 2
  gru_layers: 2
  gamma: 0.99
  deterministic: False
  num_minibatches: 2
  use_gae: True

