program: run.py
project: mazelens
name: ad_ppo_11x11_adamw_sweep

metric:
  name: success_rate
  goal: maximize

method: bayes
parameters:
  experiment:
    values: [ aj3/ad/explore/ppo_11x11 ]
  trainer.agent.lr:
    distribution: log_uniform
    min: -9.21
    max: -6.97
  trainer.agent.val_loss_coef:
    distribution: uniform
    min: 0.2
    max: 1.0
  trainer.agent.entropy_coef:
    distribution: uniform
    min: 0
    max: 0.2
  trainer.agent.max_grad_norm:
    distribution: uniform
    min: 0.5
    max: 1.0
  trainer.agent.wd:
    distribution: log_uniform
    min: -9.21
    max: -4.61



command:
  - ${env}
  - python
  - run.py
  - "+experiment=aj3/ad/explore/ppo_11x11"
  - "logger.name=null"